from __future__ import annotations

from sqlalchemy import (
    BigInteger,
    Column,
    Computed,
    Double,
    Index,
    Integer,
    MetaData,
    Table,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.mysql import LONGTEXT, VARCHAR


TABLE_PREFIX = "aics_"
VERSION_TABLE = "aics_schema_version"
metadata = MetaData()


def _id(name: str, *, primary_key: bool = False, nullable: bool = False) -> Column:
    kwargs = {
        "primary_key": primary_key,
        "nullable": nullable,
    }
    if not primary_key:
        kwargs["server_default"] = ""
    return Column(name, VARCHAR(191), **kwargs)


def _short(name: str, default: str = "", *, nullable: bool = False, length: int = 191) -> Column:
    return Column(name, VARCHAR(length), nullable=nullable, server_default=default)


def _json(name: str, default: str) -> Column:
    escaped = default.replace("'", "''")
    return Column(name, LONGTEXT, nullable=False, server_default=text(f"('{escaped}')"))


def _long(name: str, default: str = "") -> Column:
    escaped = default.replace("'", "''")
    return Column(name, LONGTEXT, nullable=False, server_default=text(f"('{escaped}')"))


def _time(name: str, default: str | None = None) -> Column:
    kwargs = {"nullable": False}
    if default is not None:
        kwargs["server_default"] = default
    return Column(name, VARCHAR(40), **kwargs)


conversations = Table(
    f"{TABLE_PREFIX}conversations",
    metadata,
    _id("id", primary_key=True),
    _id("customer_id"),
    _id("external_userid"),
    _id("corp_id"),
    _id("user_id"),
    _id("wechat"),
    _long("title"),
    _time("created_at"),
    _time("updated_at"),
    Index("idx_aics_conversations_updated_at", "updated_at"),
    Index("idx_aics_conversations_customer_id", "customer_id"),
    Index(
        "idx_aics_conversations_sales_contact",
        "corp_id",
        "wechat",
        "external_userid",
        "customer_id",
        "updated_at",
        mysql_length={
            "corp_id": 64,
            "wechat": 64,
            "external_userid": 64,
            "customer_id": 64,
        },
    ),
)

messages = Table(
    f"{TABLE_PREFIX}messages",
    metadata,
    _id("id", primary_key=True),
    _id("conversation_id"),
    _id("request_id"),
    _short("role", length=32),
    _long("content"),
    _long("file_image"),
    _json("reply_messages", "[]"),
    _time("created_at"),
    Index("idx_aics_messages_conversation_id", "conversation_id", "created_at"),
    Index("idx_aics_messages_request_id", "request_id"),
)

runs = Table(
    f"{TABLE_PREFIX}runs",
    metadata,
    _id("request_id", primary_key=True),
    _id("conversation_id"),
    _id("customer_id"),
    _json("input_snapshot", "{}"),
    _json("output_snapshot", "{}"),
    _json("intents", "[]"),
    _json("tags", "[]"),
    Column("duration_ms", BigInteger, nullable=False, server_default="0"),
    _json("token_usage", "{}"),
    _long("error"),
    _time("created_at"),
    Index("idx_aics_runs_conversation_id", "conversation_id", "created_at"),
    Index("idx_aics_runs_customer_id", "customer_id", "created_at"),
)

node_traces = Table(
    f"{TABLE_PREFIX}node_traces",
    metadata,
    _id("id", primary_key=True),
    _id("request_id"),
    _short("node_name"),
    _json("input_snapshot", "{}"),
    _json("output_snapshot", "{}"),
    _json("tool_calls", "[]"),
    Column("duration_ms", BigInteger, nullable=False, server_default="0"),
    _long("error"),
    _time("created_at"),
    Index("idx_aics_node_traces_request_id", "request_id"),
    Index("idx_aics_node_traces_node_name", "node_name"),
    Index("idx_aics_node_traces_created_at", "created_at"),
)

customer_memory = Table(
    f"{TABLE_PREFIX}customer_memory",
    metadata,
    _id("customer_id", primary_key=True),
    _json("portrait", "{}"),
    _json("basic_info", "{}"),
    _short("lifecycle_stage"),
    _time("updated_at"),
    _time("last_customer_message_at", ""),
    _time("last_staff_message_at", ""),
    _time("last_ai_reply_at", ""),
    _time("last_manual_takeover_at", ""),
    _time("last_outreach_at", ""),
    _short("outreach_status", "none", length=64),
    _id("outreach_plan_id"),
)

history_events = Table(
    f"{TABLE_PREFIX}history_events",
    metadata,
    _id("id", primary_key=True),
    _id("customer_id"),
    _short("event_type"),
    _short("stage"),
    _long("summary"),
    _json("facts", "{}"),
    _long("impact"),
    Column("confidence", Double, nullable=False, server_default="0"),
    _time("created_at"),
    Index("idx_aics_history_events_customer_id", "customer_id", "created_at"),
    Index("idx_aics_history_events_type", "event_type"),
)

outreach_sop_plans = Table(
    f"{TABLE_PREFIX}outreach_sop_plans",
    metadata,
    _id("id", primary_key=True),
    _short("name"),
    _long("description"),
    _short("status", "draft", length=64),
    _json("filters_json", "{}"),
    _time("created_at"),
    _time("updated_at"),
    _time("last_run_at", ""),
    _json("last_run_summary_json", "{}"),
    Index("idx_aics_outreach_sop_plans_status", "status", "updated_at"),
)

outreach_plans = Table(
    f"{TABLE_PREFIX}outreach_plans",
    metadata,
    _id("id", primary_key=True),
    _id("sop_plan_id"),
    _id("customer_id"),
    _id("corp_id"),
    _id("user_id"),
    _id("wechat"),
    _id("external_userid"),
    _short("status", "draft", length=64),
    _short("customer_stage"),
    _long("stall_reason"),
    _long("customer_psychology"),
    _long("plan_goal"),
    _json("source_snapshot", "{}"),
    _time("created_at"),
    _time("updated_at"),
    _time("paused_at", ""),
    _time("cancelled_at", ""),
    _time("completed_at", ""),
    Index("idx_aics_outreach_plans_customer_id", "customer_id", "created_at"),
    Index("idx_aics_outreach_plans_status", "status", "updated_at"),
    Index("idx_aics_outreach_plans_sop_plan_id", "sop_plan_id", "created_at"),
    Index(
        "idx_aics_outreach_plans_sales_contact",
        "corp_id",
        "wechat",
        "external_userid",
        "customer_id",
        "created_at",
        mysql_length={
            "corp_id": 64,
            "wechat": 64,
            "external_userid": 64,
            "customer_id": 64,
        },
    ),
)

outreach_tasks = Table(
    f"{TABLE_PREFIX}outreach_tasks",
    metadata,
    _id("id", primary_key=True),
    _id("plan_id"),
    _id("customer_id"),
    Column("step_index", Integer, nullable=False, server_default="1"),
    _time("scheduled_at", ""),
    _short("status", "pending", length=64),
    _short("intent"),
    _long("message_goal"),
    _json("content_sources", "[]"),
    _json("reply_messages_json", "[]"),
    Column("before_send_check", Integer, nullable=False, server_default="1"),
    _time("sent_at", ""),
    _short("send_status"),
    _id("system_msgid"),
    _long("error_message"),
    _time("created_at"),
    _time("updated_at"),
    Index("idx_aics_outreach_tasks_plan_id", "plan_id", "step_index"),
    Index("idx_aics_outreach_tasks_due", "status", "scheduled_at"),
    Index("idx_aics_outreach_tasks_customer_id", "customer_id", "scheduled_at"),
)

outreach_events = Table(
    f"{TABLE_PREFIX}outreach_events",
    metadata,
    _id("id", primary_key=True),
    _id("plan_id"),
    _id("task_id"),
    _id("customer_id"),
    _short("event_type"),
    _long("event_summary"),
    _json("payload_json", "{}"),
    _time("created_at"),
    Index("idx_aics_outreach_events_plan_id", "plan_id", "created_at"),
    Index("idx_aics_outreach_events_customer_id", "customer_id", "created_at"),
)

first_day_outreach_runs = Table(
    f"{TABLE_PREFIX}first_day_outreach_runs",
    metadata,
    _id("workflow_run_id", primary_key=True),
    _id("plan_id"),
    _id("first_task_id"),
    _id("second_task_id"),
    _id("corp_id"),
    _id("user_id"),
    _id("wechat"),
    _id("customer_id"),
    _id("external_userid"),
    _short("trigger_type", length=64),
    Column("conversation_fingerprint", VARCHAR(64), nullable=True),
    _time("next_retry_at", ""),
    _short("status", "running", length=64),
    _short("reason_code", length=128),
    _short("final_decision", length=64),
    _short("first_scene", length=64),
    _short("second_scene", length=64),
    Column("model_attempt_count", Integer, nullable=False, server_default="0"),
    Column("retry_count", Integer, nullable=False, server_default="0"),
    Column("duration_ms", BigInteger, nullable=False, server_default="0"),
    _json("input_snapshot_json", "{}"),
    _json("workflow_json", "{}"),
    _json("final_plan_json", "{}"),
    _short("error_node", length=128),
    _short("error_type", length=128),
    _long("error_message"),
    _time("started_at"),
    _time("finished_at", ""),
    _time("raw_redacted_at", ""),
    _time("created_at"),
    _time("updated_at"),
    Index("idx_aics_first_day_runs_started", "started_at", "workflow_run_id"),
    Index("idx_aics_first_day_runs_status", "status", "started_at"),
    Index("idx_aics_first_day_runs_plan", "plan_id"),
    Index(
        "idx_aics_first_day_runs_contact_fingerprint",
        "corp_id",
        "wechat",
        "external_userid",
        "customer_id",
        "trigger_type",
        "conversation_fingerprint",
        unique=True,
        mysql_length={
            "corp_id": 48,
            "wechat": 48,
            "external_userid": 48,
            "customer_id": 48,
        },
    ),
    Index(
        "idx_aics_first_day_runs_contact",
        "corp_id",
        "wechat",
        "external_userid",
        "customer_id",
        "started_at",
        mysql_length={
            "corp_id": 48,
            "wechat": 48,
            "external_userid": 48,
            "customer_id": 48,
        },
    ),
)

sop_events = Table(
    f"{TABLE_PREFIX}sop_events",
    metadata,
    _id("id"),
    _id("event_id", primary_key=True),
    _short("event_type"),
    _short("source"),
    Column("request_reply", Integer, nullable=False, server_default="0"),
    _time("upstream_created_at", ""),
    _json("raw_payload_json", "{}"),
    _short("status", "accepted", length=64),
    _long("error"),
    Column("retry_count", Integer, nullable=False, server_default="0"),
    _time("next_retry_at", ""),
    _long("last_retry_error"),
    _time("received_at"),
    _time("updated_at"),
    Index("idx_aics_sop_events_id", "id"),
    Index("idx_aics_sop_events_type", "event_type", "received_at"),
    Index("idx_aics_sop_events_status", "status", "updated_at"),
    Index("idx_aics_sop_events_retry", "status", "next_retry_at"),
)

sop_send_tasks = Table(
    f"{TABLE_PREFIX}sop_send_tasks",
    metadata,
    _id("id", primary_key=True),
    _id("event_id"),
    _id("idempotency_key"),
    _id("send_once_key"),
    _id("customer_id"),
    _id("external_userid"),
    _id("corp_id"),
    _id("user_id"),
    _id("wechat"),
    _id("sop_pack_id"),
    _short("sop_pack_name"),
    _short("sop_category"),
    _short("trigger_source"),
    _json("reply_messages_json", "[]"),
    _short("status", "pending", length=64),
    _json("send_payload_json", "{}"),
    _json("send_response_json", "{}"),
    _long("error"),
    _time("created_at"),
    _time("updated_at"),
    _time("sent_at", ""),
    Column(
        "active_send_once_key",
        VARCHAR(191),
        Computed(
            "CASE WHEN send_once_key <> '' AND status IN ('pending','sent') "
            "THEN send_once_key ELSE NULL END",
            persisted=True,
        ),
    ),
    UniqueConstraint("idempotency_key", name="uq_aics_sop_send_tasks_idempotency"),
    Index("uq_aics_sop_send_tasks_active_once", "active_send_once_key", unique=True),
    Index("idx_aics_sop_send_tasks_event_id", "event_id", "created_at"),
    Index("idx_aics_sop_send_tasks_customer", "customer_id", "created_at"),
    Index("idx_aics_sop_send_tasks_pack", "sop_pack_id", "status", "created_at"),
    Index("idx_aics_sop_send_tasks_category", "sop_category", "status", "created_at"),
    Index(
        "idx_aics_sop_send_tasks_sales_contact",
        "corp_id",
        "wechat",
        "external_userid",
        "customer_id",
        "status",
        "created_at",
        mysql_length={
            "corp_id": 64,
            "wechat": 64,
            "external_userid": 64,
            "customer_id": 64,
            "status": 32,
        },
    ),
)

strategy_data_outbox = Table(
    f"{TABLE_PREFIX}strategy_data_outbox",
    metadata,
    _id("id", primary_key=True),
    _id("idempotency_key"),
    _short("record_kind", length=64),
    _id("task_id"),
    _id("sales_contact_key"),
    _id("customer_id"),
    _short("interface_version", length=32),
    _json("payload_json", "{}"),
    _short("status", "pending", length=32),
    Column("retry_count", Integer, nullable=False, server_default="0"),
    _time("next_retry_at", ""),
    _json("response_json", "{}"),
    _long("error"),
    _time("created_at"),
    _time("updated_at"),
    _time("sent_at", ""),
    UniqueConstraint("idempotency_key", name="uq_aics_strategy_data_outbox_idempotency"),
    Index("idx_aics_strategy_data_outbox_due", "status", "next_retry_at", "created_at"),
    Index("idx_aics_strategy_data_outbox_contact", "sales_contact_key", "created_at"),
)


message_dispatches = Table(
    f"{TABLE_PREFIX}message_dispatches",
    metadata,
    _id("id", primary_key=True),
    _id("idempotency_key"),
    _short("source_channel", length=64),
    _short("source_kind", length=64),
    _id("source_request_id"),
    _id("source_task_id"),
    _id("conversation_id"),
    _id("corp_id"),
    _id("customer_id"),
    _id("external_userid"),
    _id("user_id"),
    _id("wechat"),
    _id("plan_id"),
    _id("task_id"),
    _json("reply_messages_json", "[]"),
    _json("source_context_json", "{}"),
    _short("status", "created", length=64),
    Column("expected_count", Integer, nullable=False, server_default="0"),
    Column("succeeded_count", Integer, nullable=False, server_default="0"),
    Column("failed_count", Integer, nullable=False, server_default="0"),
    _id("platform_request_id"),
    _id("system_msgid"),
    _long("error_code"),
    _long("error_message"),
    _time("submitted_at", ""),
    _time("accepted_at", ""),
    _time("confirmed_at", ""),
    _time("last_callback_at", ""),
    _time("finalized_at", ""),
    _time("created_at"),
    _time("updated_at"),
    UniqueConstraint("idempotency_key", name="uq_aics_message_dispatches_idempotency"),
    Index("idx_aics_message_dispatches_status", "status", "updated_at"),
    Index("idx_aics_message_dispatches_task", "task_id", "created_at"),
    Index(
        "idx_aics_message_dispatches_sales_contact",
        "corp_id",
        "wechat",
        "external_userid",
        "customer_id",
        "created_at",
        mysql_length={
            "corp_id": 64,
            "wechat": 64,
            "external_userid": 64,
            "customer_id": 64,
        },
    ),
)

message_dispatch_items = Table(
    f"{TABLE_PREFIX}message_dispatch_items",
    metadata,
    _id("id", primary_key=True),
    _id("dispatch_id"),
    _id("client_message_id"),
    Column("message_index", Integer, nullable=False, server_default="0"),
    _short("message_type", length=64),
    _id("payload_hash"),
    _short("status", "created", length=64),
    _id("platform_message_id"),
    _long("error_code"),
    _long("error_message"),
    _time("sent_at", ""),
    _time("created_at"),
    _time("updated_at"),
    UniqueConstraint("client_message_id", name="uq_aics_message_dispatch_items_client_id"),
    Index("idx_aics_message_dispatch_items_dispatch", "dispatch_id", "message_index"),
    Index("idx_aics_message_dispatch_items_status", "status", "updated_at"),
)

message_delivery_events = Table(
    f"{TABLE_PREFIX}message_delivery_events",
    metadata,
    _id("event_id", primary_key=True),
    _id("dispatch_id"),
    _short("status", length=64),
    _json("raw_payload_json", "{}"),
    _time("occurred_at", ""),
    _time("received_at"),
    Index("idx_aics_message_delivery_events_dispatch", "dispatch_id", "received_at"),
    Index("idx_aics_message_delivery_events_status", "status", "received_at"),
)

v3_strategy_usage_events = Table(
    f"{TABLE_PREFIX}v3_strategy_usage_events",
    metadata,
    _id("id", primary_key=True),
    _id("request_id"),
    _id("conversation_id"),
    _id("customer_id"),
    _id("corp_id"),
    _id("wechat"),
    _id("external_userid"),
    _id("user_id"),
    _id("sales_contact_key"),
    _time("occurred_at"),
    Column("checkpoint_type_id", Integer, nullable=False, server_default="0"),
    _short("checkpoint_code", length=64),
    _short("checkpoint_name"),
    Column("checkpoint_tag_id", Integer, nullable=False, server_default="0"),
    _short("checkpoint_tag_name"),
    _short("friction_status", length=64),
    _id("sequence_id"),
    _short("sequence_name"),
    _id("sequence_step_id"),
    _short("action_code", length=64),
    _short("action_name"),
    _id("script_id"),
    _short("script_code", length=128),
    _short("script_name"),
    _short("script_match_scope", length=128),
    Column("matched_count", Integer, nullable=False, server_default="0"),
    Column("candidate_count", Integer, nullable=False, server_default="0"),
    Column("sequence_candidate_count", Integer, nullable=False, server_default="0"),
    Column("script_candidate_count", Integer, nullable=False, server_default="0"),
    Column("adopted", Integer, nullable=False, server_default="0"),
    _id("dispatch_id"),
    _short("delivery_status", length=64),
    _time("delivered_at", ""),
    _long("failed_reason"),
    _short("reply_source", length=128),
    _short("reply_action", length=128),
    _short("intent_code", length=128),
    _short("closing_strategy_code", length=128),
    _short("emotion_before", length=128),
    _short("emotion_after", length=128),
    _short("policy_version", length=128),
    _short("decision_status", length=64),
    _short("intent_confidence", length=32),
    _json("intent_secondary_json", "[]"),
    _short("emotion_confidence", length=32),
    _short("emotion_pressure", length=32),
    _short("emotion_flow_action", length=64),
    _short("closing_action", length=32),
    _short("closing_node_key", length=128),
    _short("closing_trigger", length=64),
    _short("closing_customer_state", length=64),
    _short("closing_pressure", length=32),
    _json("closing_rule_ids_json", "[]"),
    _short("closing_primary_rule_id", length=128),
    _id("closing_sequence_source_id"),
    _id("closing_node_source_id"),
    Column("closing_action_type_id", Integer, nullable=False, server_default="0"),
    _short("closing_action_type_name"),
    Column("closing_script_type_id", Integer, nullable=False, server_default="0"),
    _short("closing_script_type_name"),
    _short("closing_catalog_checksum", length=128),
    _short("closing_catalog_status", length=64),
    _short("closing_rule_match_status", length=64),
    _short("closing_constraint_status", length=64),
    _json("closing_constraint_reasons_json", "[]"),
    _short("cardpoint_category_key", length=128),
    _short("cardpoint_state", length=32),
    _json("decision_reasons_json", "[]"),
    _json("decision_evidence_refs_json", "{}"),
    _short("selector_status", length=64),
    Column("fallback_used", Integer, nullable=False, server_default="0"),
    _json("payload_json", "{}"),
    _json("order_state_before_json", "{}"),
    Column("customer_turn_eligible", Integer, nullable=False, server_default="1"),
    _time("created_at"),
    _time("updated_at"),
    UniqueConstraint("request_id", name="uq_aics_v3_strategy_usage_request"),
    Index("idx_aics_v3_strategy_usage_occurred", "occurred_at"),
    Index(
        "idx_aics_v3_strategy_usage_contact",
        "corp_id",
        "wechat",
        "external_userid",
        "customer_id",
        "occurred_at",
        mysql_length={
            "corp_id": 48,
            "wechat": 48,
            "external_userid": 48,
            "customer_id": 48,
        },
    ),
    Index("idx_aics_v3_strategy_usage_checkpoint", "checkpoint_code", "checkpoint_tag_id", "occurred_at"),
    Index("idx_aics_v3_strategy_usage_sequence", "sequence_id", "occurred_at"),
    Index("idx_aics_v3_strategy_usage_script", "script_id", "occurred_at"),
    Index("idx_aics_v3_strategy_usage_action", "action_code", "occurred_at"),
    Index("idx_aics_v3_strategy_usage_dispatch", "dispatch_id"),
    Index("idx_aics_v3_strategy_usage_intent", "intent_code", "occurred_at"),
    Index("idx_aics_v3_strategy_usage_emotion", "emotion_before", "occurred_at"),
    Index("idx_aics_v3_strategy_usage_closing", "closing_strategy_code", "closing_action", "occurred_at"),
    Index(
        "idx_aics_v3_strategy_usage_closing_catalog",
        "closing_catalog_status",
        "closing_rule_match_status",
        "occurred_at",
    ),
    Index("idx_aics_v3_strategy_usage_closing_rule", "closing_primary_rule_id", "occurred_at"),
    Index("idx_aics_v3_strategy_usage_decision", "decision_status", "occurred_at"),
)

v3_strategy_outcome_events = Table(
    f"{TABLE_PREFIX}v3_strategy_outcome_events",
    metadata,
    _id("usage_event_id", primary_key=True),
    Column("customer_replied_1h", Integer, nullable=False, server_default="0"),
    Column("customer_replied_6h", Integer, nullable=False, server_default="0"),
    Column("customer_replied_24h", Integer, nullable=False, server_default="0"),
    Column("customer_replied_72h", Integer, nullable=False, server_default="0"),
    _time("first_reply_after_at", ""),
    _id("first_reply_after_msgid"),
    _short("order_state_before", length=64),
    _short("order_state_after_24h", length=64),
    _short("order_state_after_72h", length=64),
    _short("order_state_after_7d", length=64),
    _short("order_state_after_14d", length=64),
    _short("order_state_after_30d", length=64),
    Column("paid_after_24h", Integer, nullable=False, server_default="0"),
    Column("paid_after_72h", Integer, nullable=False, server_default="0"),
    Column("paid_after_7d", Integer, nullable=False, server_default="0"),
    Column("scheduled_after_7d", Integer, nullable=False, server_default="0"),
    Column("visited_after_14d", Integer, nullable=False, server_default="0"),
    Column("finished_after_30d", Integer, nullable=False, server_default="0"),
    _short("attribution_source", "local_windows", length=64),
    _id("next_usage_event_id"),
    _short("next_intent_code", length=128),
    _short("next_emotion_code", length=128),
    _short("emotion_transition", length=191),
    _short("attribution_anchor_source", "unknown", length=64),
    _short("order_source", length=128),
    _short("order_query_status", length=64),
    _long("order_query_error"),
    _time("order_last_refreshed_at", ""),
    _json("payload_json", "{}"),
    _time("created_at"),
    _time("updated_at"),
    Index("idx_aics_v3_strategy_outcome_updated", "updated_at"),
)


EXPECTED_TABLES = tuple(sorted(table.name for table in metadata.tables.values()))
EXPECTED_ALL_TABLES = tuple(sorted((*EXPECTED_TABLES, VERSION_TABLE)))
EXPECTED_COLUMNS = {
    table.name: tuple(column.name for column in table.columns)
    for table in metadata.tables.values()
}
EXPECTED_INDEXES: dict[str, dict[str, tuple[str, ...]]] = {}
for _table in metadata.tables.values():
    _indexes: dict[str, tuple[str, ...]] = {}
    _primary = tuple(column.name for column in _table.primary_key.columns)
    if _primary:
        _indexes["PRIMARY"] = _primary
    for _constraint in _table.constraints:
        if isinstance(_constraint, UniqueConstraint) and _constraint.name:
            _indexes[_constraint.name] = tuple(column.name for column in _constraint.columns)
    for _index in _table.indexes:
        _indexes[_index.name] = tuple(column.name for column in _index.columns)
    EXPECTED_INDEXES[_table.name] = _indexes
