from __future__ import annotations

from app.policies.identity_policy import FORBIDDEN_IDENTITY_TERMS


REPLY_HARD_FORBIDDEN_TERMS = (
    *FORBIDDEN_IDENTITY_TERMS,
    "包接送",
    "免费接送",
    "安排接送",
    "支持接送",
    "可以接送",
    "车费报销",
    "报销车费",
    "打车报销",
    "报销打车",
    "打车凭证",
    "打车发票",
    "实报实销",
    "报销准备",
    "报销细节",
    "3公里内接送",
    "3公里接送",
    "3公里内到店",
    "车费补贴",
    "交通补贴",
    "医美",
    "医疗美容",
    "正规皮肤管理机构",
    "正规备案",
    "备案皮肤管理机构",
    "官方备案",
    "卫健委",
    "官网核验",
    "官方认证",
    "官方认证入口",
    "官方查询",
    "国家企业信用信息公示系统",
    "企业信用信息公示",
    "官方渠道核验",
    "企业微信官方认证入口",
    "平台可溯",
    "营业执照",
    "设备注册证",
    "设备备案",
    "CFDA",
    "进口仪器",
    "执业许可证",
    "持证皮肤管理机构",
    "持证上岗",
    "持证技师",
    "持证老师",
    "持证合规",
    "主诊老师证",
    "激光操作上岗证",
    "NMPA",
    "临床",
    "更安全",
    "所有门店都持有",
    "所有门店都有资质",
    "所有门店均有资质",
    "所有门店均持资质",
    "所有门店均为持证",
    "所有门店均具备",
    "所有门店都是备案",
    "所有门店资质合规",
    "操作老师均持有",
    "老师均持有",
    "绝无",
    "绝对安全",
    "保证效果",
    "包效果",
    "100%见效",
    "百分百见效",
    "根治",
    "一次根治",
    "一次一定好",
    "一定有效",
    "肯定有效",
    "不伤肤",
    "不伤害皮肤",
    "不会伤害皮肤",
    "不会伤皮肤",
    "不会伤肤",
    "不会留疤",
    "不会留痕",
    "留疤概率很低",
    "不留疤",
    "国内最好的",
    "效果最好",
    "最好的效果",
    "返现",
    "真人客服",
    "我不是AI",
    "我不是机器人",
    "系统查询",
    "系统可查",
    "系统里",
    "工具返回",
    "知识库",
    "检索结果",
    "内部分析",
    "判断依据",
    "reply_brief",
    "module_outputs",
    "route_result",
    "subflow",
    "intent",
    "debug",
    "调试信息",
    "转人工",
    "转接",
    "转人",
    "转过去",
    "帮您转",
)

REPLY_THIRD_PERSON_CUSTOMER_TERMS = (
    "客户当前",
    "客户提到",
    "客户表示",
    "客户偏好",
    "客户问题",
)

REPLY_PRICE_RULE_TERMS = (
    "活动价",
    "体验价",
    "最终体验价",
    "定金",
    "尾款",
    "多退少补",
    "到店再付",
    "锁定名额",
)

REPLY_LONG_FORM_TASK_TYPES = {
    "store_inquiry",
    "appointment",
    "appointment_status",
    "appointment_change",
    "appointment_cancel",
}

REPLY_MAX_TEXT_MESSAGE_CHARS = 180
REPLY_MAX_TEXT_MESSAGE_CHARS_LONG_FORM = 260
REPLY_MAX_TOTAL_TEXT_CHARS = 300
REPLY_MAX_TOTAL_TEXT_CHARS_LONG_FORM = 460
